import {
  EnemyType,
  DungeonType,
  PlayerZone,
  ShootingPatternType,
  MovementPatternType,
  IdleIntensity,
  RealmBiome,
  DifficultyZone,
  DamageType,
  RealmTier,
  getZoneBase,
} from "./types";

// --- Enemy Definition ---

export type EnemyShape =
  | "circle"
  | "diamond"
  | "triangle"
  | "square"
  | "hexagon"
  | "star";

export interface EnemyDefinition {
  type: number;
  biome: number;
  name: string;
  hp: number;
  speed: number;
  radius: number;
  aggroRange: number;
  leashRange: number;
  shootCooldown: number; // ms
  projectileDamage: number;
  projectileSpeed: number;
  projectileRange: number;
  shootingPattern: number;
  xpValue: number;
  shape: EnemyShape;
  color: number;
  projectileCollisionRadius?: number;
  difficultyZone?: number; // DifficultyZone value (realm overworld only)
  biomeAffinity?: number[]; // RealmBiome values this enemy prefers
  movementPattern?: number; // MovementPatternType value (realm overworld only)
  idleIntensity?: number; // IdleIntensity value (0=low, 1=medium, 2=high)
  dungeonDrop?: number; // DungeonType value — this enemy drops a portal for this dungeon
  dungeonDropChance?: number; // 0–1 probability of dropping the dungeon portal on kill (requires dungeonDrop)
  defaultDamageType?: number; // DamageType value (0=Physical, 1=Magic); defaults to Physical
  realmTier?: number; // RealmTier value (1=Wild, 2=Ruins, 3=DevineHell); undefined defaults to tier 1
}

// --- Pack (cluster) enemy definitions ---

export interface PackDefinition {
  leaderType: number;
  minionType: number;
  minionCount: number;
  respawnCooldown: number; // ms — how often leader respawns dead minions
}

export const PACK_DEFS: Record<number, PackDefinition> = {
  [EnemyType.BriarBeast]: {
    leaderType: EnemyType.BriarBeast,
    minionType: EnemyType.BriarImp,
    minionCount: 3,
    respawnCooldown: 8000,
  },
  [EnemyType.BroodMother]: {
    leaderType: EnemyType.BroodMother,
    minionType: EnemyType.Broodling,
    minionCount: 4,
    respawnCooldown: 6000,
  },
  [EnemyType.FrostMatriarch]: {
    leaderType: EnemyType.FrostMatriarch,
    minionType: EnemyType.FrostSprite,
    minionCount: 3,
    respawnCooldown: 10000,
  },
  // T2 Packs
  [EnemyType.PlagueBrood]: {
    leaderType: EnemyType.PlagueBrood,
    minionType: EnemyType.PlagueRat,
    minionCount: 3,
    respawnCooldown: 8000,
  },
  [EnemyType.CursedMatron]: {
    leaderType: EnemyType.CursedMatron,
    minionType: EnemyType.CursedSpawn,
    minionCount: 4,
    respawnCooldown: 6000,
  },
  [EnemyType.AshMatriarch]: {
    leaderType: EnemyType.AshMatriarch,
    minionType: EnemyType.AshSprite,
    minionCount: 3,
    respawnCooldown: 10000,
  },
  // T3 Packs
  [EnemyType.DemonBroodmother]: {
    leaderType: EnemyType.DemonBroodmother,
    minionType: EnemyType.DemonWhelp,
    minionCount: 3,
    respawnCooldown: 8000,
  },
  [EnemyType.SoulHarvester]: {
    leaderType: EnemyType.SoulHarvester,
    minionType: EnemyType.LostSoul,
    minionCount: 4,
    respawnCooldown: 6000,
  },
  [EnemyType.DoomMatriarch]: {
    leaderType: EnemyType.DoomMatriarch,
    minionType: EnemyType.DoomSprite,
    minionCount: 3,
    respawnCooldown: 10000,
  },
};

export function isPackLeader(type: number): boolean {
  return type in PACK_DEFS;
}

export function getPackDef(type: number): PackDefinition | undefined {
  return PACK_DEFS[type];
}

// --- All Enemy Definitions (populated by realm + dungeon defs below) ---

export const ENEMY_DEFS: Record<number, EnemyDefinition> = {};

// ===== NEW REALM OVERWORLD ENEMIES (15 enemies, 3 per difficulty tier) =====

export const REALM_ENEMY_DEFS: Record<number, EnemyDefinition> = {
  // ===== SHORE - Tier 1 (DifficultyZone.Shore) =====
  [EnemyType.HermitCrab]: {
    type: EnemyType.HermitCrab,
    biome: 0, // not used for realm enemies
    name: "Hermit Crab",
    hp: 50,
    speed: 35,
    radius: 14,
    aggroRange: 180,
    leashRange: 350,
    shootCooldown: 2000,
    projectileDamage: 10,
    projectileSpeed: 120,
    projectileRange: 300,
    shootingPattern: ShootingPatternType.SingleAimed,
    movementPattern: MovementPatternType.WanderingSprayer,
    xpValue: 8,
    shape: "circle",
    color: 0xcc8866,
    difficultyZone: DifficultyZone.Shore,
    biomeAffinity: [RealmBiome.WildShore, RealmBiome.WildPlains],
  },
  [EnemyType.Frog]: {
    type: EnemyType.Frog,
    biome: 0,
    name: "Frog",
    hp: 35,
    speed: 55,
    radius: 11,
    aggroRange: 200,
    leashRange: 320,
    shootCooldown: 2200,
    projectileDamage: 8,
    projectileSpeed: 120,
    projectileRange: 280,
    shootingPattern: ShootingPatternType.Spread3,
    movementPattern: MovementPatternType.Shotgunner,
    xpValue: 7,
    shape: "diamond",
    color: 0x44aa44,
    difficultyZone: DifficultyZone.Shore,
    biomeAffinity: [RealmBiome.WildMarsh, RealmBiome.WildMeadow],
  },
  [EnemyType.Sandpiper]: {
    type: EnemyType.Sandpiper,
    biome: 0,
    name: "Sandpiper",
    hp: 25,
    speed: 70,
    radius: 10,
    aggroRange: 220,
    leashRange: 380,
    shootCooldown: 1800,
    projectileDamage: 6,
    projectileSpeed: 120,
    projectileRange: 320,
    shootingPattern: ShootingPatternType.SingleAimed,
    movementPattern: MovementPatternType.WanderingSprayer,
    idleIntensity: IdleIntensity.High,
    xpValue: 5,
    shape: "triangle",
    color: 0xccaa88,
    difficultyZone: DifficultyZone.Shore,
    biomeAffinity: [RealmBiome.WildShore, RealmBiome.WildMarsh, RealmBiome.WildPlains],
  },

  // ===== LOWLANDS - Tier 2 (DifficultyZone.Lowlands) =====
  [EnemyType.Wolf]: {
    type: EnemyType.Wolf,
    biome: 0,
    name: "Wolf",
    hp: 250,
    speed: 80,
    radius: 14,
    aggroRange: 280,
    leashRange: 480,
    shootCooldown: 1200,
    projectileDamage: 14,
    projectileSpeed: 120,
    projectileRange: 380,
    shootingPattern: ShootingPatternType.SingleAimed,
    movementPattern: MovementPatternType.WanderingSprayer,
    idleIntensity: IdleIntensity.Medium,
    xpValue: 40,
    shape: "triangle",
    color: 0x888888,
    difficultyZone: DifficultyZone.Lowlands,
    biomeAffinity: [RealmBiome.WildMeadow, RealmBiome.WildForest],
  },
  [EnemyType.Rattlesnake]: {
    type: EnemyType.Rattlesnake,
    biome: 0,
    name: "Rattlesnake",
    hp: 160,
    speed: 60,
    radius: 12,
    aggroRange: 250,
    leashRange: 420,
    shootCooldown: 1200,
    projectileDamage: 16,
    projectileSpeed: 120,
    projectileRange: 350,
    shootingPattern: ShootingPatternType.Spread3,
    movementPattern: MovementPatternType.ChargerRetreater,
    xpValue: 30,
    shape: "diamond",
    color: 0xaa8844,
    difficultyZone: DifficultyZone.Lowlands,
    biomeAffinity: [RealmBiome.WildDesert, RealmBiome.WildPlains, RealmBiome.WildShrubland],
  },
  [EnemyType.BogLurker]: {
    type: EnemyType.BogLurker,
    biome: 0,
    name: "Bog Lurker",
    hp: 420,
    speed: 30,
    radius: 16,
    aggroRange: 220,
    leashRange: 380,
    shootCooldown: 1800,
    projectileDamage: 12,
    projectileSpeed: 120,
    projectileRange: 350,
    shootingPattern: ShootingPatternType.BurstRing4,
    movementPattern: MovementPatternType.RingPulser,
    xpValue: 55,
    shape: "hexagon",
    color: 0x446644,
    difficultyZone: DifficultyZone.Lowlands,
    biomeAffinity: [RealmBiome.WildMarsh, RealmBiome.WildJungle],
    defaultDamageType: DamageType.Magic,
  },

  // ===== MIDLANDS - Tier 3 (DifficultyZone.Midlands) =====
  [EnemyType.ForestGuardian]: {
    type: EnemyType.ForestGuardian,
    biome: 0,
    name: "Forest Guardian",
    hp: 1400,
    speed: 30,
    radius: 20,
    aggroRange: 250,
    leashRange: 420,
    shootCooldown: 1400,
    projectileDamage: 18,
    projectileSpeed: 120,
    projectileRange: 420,
    shootingPattern: ShootingPatternType.Spread5,
    movementPattern: MovementPatternType.SpiralSpinner,
    xpValue: 130,
    shape: "square",
    color: 0x2a6a2a,
    difficultyZone: DifficultyZone.Midlands,
    biomeAffinity: [RealmBiome.WildForest, RealmBiome.WildTaiga],
  },
  [EnemyType.DustDevil]: {
    type: EnemyType.DustDevil,
    biome: 0,
    name: "Dust Devil",
    hp: 700,
    speed: 90,
    radius: 14,
    aggroRange: 300,
    leashRange: 500,
    shootCooldown: 1000,
    projectileDamage: 22,
    projectileSpeed: 120,
    projectileRange: 400,
    shootingPattern: ShootingPatternType.Spiral3,
    movementPattern: MovementPatternType.SpiralSpinner,
    idleIntensity: IdleIntensity.High,
    xpValue: 85,
    shape: "diamond",
    color: 0xccaa66,
    difficultyZone: DifficultyZone.Midlands,
    biomeAffinity: [RealmBiome.WildDesert, RealmBiome.WildShrubland, RealmBiome.WildCliffs],
    defaultDamageType: DamageType.Magic,
  },
  [EnemyType.JungleStalker]: {
    type: EnemyType.JungleStalker,
    biome: 0,
    name: "Jungle Stalker",
    hp: 850,
    speed: 75,
    radius: 14,
    aggroRange: 320,
    leashRange: 520,
    shootCooldown: 900,
    projectileDamage: 20,
    projectileSpeed: 120,
    projectileRange: 420,
    shootingPattern: ShootingPatternType.DoubleSingle,
    movementPattern: MovementPatternType.BurstMage,
    idleIntensity: IdleIntensity.Medium,
    xpValue: 100,
    shape: "triangle",
    color: 0x226622,
    difficultyZone: DifficultyZone.Midlands,
    biomeAffinity: [RealmBiome.WildJungle, RealmBiome.WildForest],
  },

  // ===== HIGHLANDS - Tier 4 (DifficultyZone.Highlands) =====
  [EnemyType.FrostWarden]: {
    type: EnemyType.FrostWarden,
    biome: 0,
    name: "Frost Warden",
    hp: 2600,
    speed: 55,
    radius: 18,
    aggroRange: 300,
    leashRange: 500,
    shootCooldown: 1000,
    projectileDamage: 26,
    projectileSpeed: 120,
    projectileRange: 440,
    shootingPattern: ShootingPatternType.BurstRing8,
    movementPattern: MovementPatternType.BurstMage,
    xpValue: 300,
    shape: "star",
    color: 0x88bbdd,
    difficultyZone: DifficultyZone.Highlands,
    biomeAffinity: [RealmBiome.WildPeaks, RealmBiome.WildTundra],
    defaultDamageType: DamageType.Magic,
  },
  [EnemyType.CliffDrake]: {
    type: EnemyType.CliffDrake,
    biome: 0,
    name: "Cliff Drake",
    hp: 1800,
    speed: 100,
    radius: 14,
    aggroRange: 340,
    leashRange: 580,
    shootCooldown: 700,
    projectileDamage: 26,
    projectileSpeed: 120,
    projectileRange: 420,
    shootingPattern: ShootingPatternType.Spread3,
    movementPattern: MovementPatternType.Orbiter,
    idleIntensity: IdleIntensity.Medium,
    xpValue: 240,
    shape: "triangle",
    color: 0x886644,
    difficultyZone: DifficultyZone.Highlands,
    biomeAffinity: [RealmBiome.WildCliffs, RealmBiome.WildVolcanic, RealmBiome.WildTaiga],
  },
  [EnemyType.StormElemental]: {
    type: EnemyType.StormElemental,
    biome: 0,
    name: "Storm Elemental",
    hp: 3200,
    speed: 40,
    radius: 20,
    aggroRange: 280,
    leashRange: 460,
    shootCooldown: 1200,
    projectileDamage: 28,
    projectileSpeed: 120,
    projectileRange: 450,
    shootingPattern: ShootingPatternType.BurstRing12,
    movementPattern: MovementPatternType.Orbiter,
    xpValue: 350,
    shape: "hexagon",
    color: 0x6688cc,
    difficultyZone: DifficultyZone.Highlands,
    biomeAffinity: [RealmBiome.WildTundra, RealmBiome.WildPeaks, RealmBiome.WildCliffs],
    defaultDamageType: DamageType.Magic,
  },

  // ===== GODLANDS - Tier 5 (DifficultyZone.Godlands) =====
  [EnemyType.FallenSeraph]: {
    type: EnemyType.FallenSeraph,
    biome: 0,
    name: "Fallen Seraph",
    hp: 7500,
    speed: 65,
    radius: 20,
    aggroRange: 400,
    leashRange: 640,
    shootCooldown: 900,
    projectileDamage: 48,
    projectileSpeed: 120,
    projectileRange: 500,
    shootingPattern: ShootingPatternType.BurstRing8,
    movementPattern: MovementPatternType.Shotgunner,
    xpValue: 750,
    shape: "star",
    color: 0xffcc44,
    difficultyZone: DifficultyZone.Godlands,
    biomeAffinity: [RealmBiome.WildPeaks, RealmBiome.WildVolcanic],
    defaultDamageType: DamageType.Magic,
  },
  [EnemyType.VoidWalker]: {
    type: EnemyType.VoidWalker,
    biome: 0,
    name: "Void Walker",
    hp: 4500,
    speed: 95,
    radius: 14,
    aggroRange: 360,
    leashRange: 580,
    shootCooldown: 500,
    projectileDamage: 38,
    projectileSpeed: 120,
    projectileRange: 460,
    shootingPattern: ShootingPatternType.Spread5,
    movementPattern: MovementPatternType.BurstMage,
    idleIntensity: IdleIntensity.Medium,
    xpValue: 550,
    shape: "diamond",
    color: 0x9922cc,
    difficultyZone: DifficultyZone.Godlands,
    biomeAffinity: [RealmBiome.WildTundra, RealmBiome.WildVolcanic, RealmBiome.WildCliffs],
    defaultDamageType: DamageType.Magic,
  },
  [EnemyType.AncientTitan]: {
    type: EnemyType.AncientTitan,
    biome: 0,
    name: "Ancient Titan",
    hp: 9000,
    speed: 30,
    radius: 24,
    aggroRange: 320,
    leashRange: 520,
    shootCooldown: 1000,
    projectileDamage: 55,
    projectileSpeed: 120,
    projectileRange: 500,
    shootingPattern: ShootingPatternType.Spiral8,
    movementPattern: MovementPatternType.RingPulser,
    xpValue: 900,
    shape: "square",
    color: 0x442266,
    difficultyZone: DifficultyZone.Godlands,
    biomeAffinity: [RealmBiome.WildPeaks, RealmBiome.WildTundra, RealmBiome.WildVolcanic],
    dungeonDrop: DungeonType.InfernalPit,
    dungeonDropChance: 0.3,
  },

  // ===== SHORE - Tier 1 (NEW) =====
  [EnemyType.Jellyfish]: {
    type: EnemyType.Jellyfish,
    biome: 0,
    name: "Jellyfish",
    hp: 40,
    speed: 25,
    radius: 12,
    aggroRange: 200,
    leashRange: 340,
    shootCooldown: 2000,
    projectileDamage: 8,
    projectileSpeed: 120,
    projectileRange: 300,
    shootingPattern: ShootingPatternType.BurstRing4,
    movementPattern: MovementPatternType.RingPulser,
    xpValue: 8,
    shape: "circle",
    color: 0x88bbff,
    difficultyZone: DifficultyZone.Shore,
    biomeAffinity: [RealmBiome.WildShore, RealmBiome.WildMarsh],
    defaultDamageType: DamageType.Magic,
  },
  [EnemyType.CoconutCrab]: {
    type: EnemyType.CoconutCrab,
    biome: 0,
    name: "Coconut Crab",
    hp: 65,
    speed: 60,
    radius: 14,
    aggroRange: 190,
    leashRange: 360,
    shootCooldown: 1800,
    projectileDamage: 12,
    projectileSpeed: 120,
    projectileRange: 280,
    shootingPattern: ShootingPatternType.Spread3,
    movementPattern: MovementPatternType.ChargerRetreater,
    xpValue: 10,
    shape: "square",
    color: 0xbb6633,
    difficultyZone: DifficultyZone.Shore,
    biomeAffinity: [RealmBiome.WildShore, RealmBiome.WildPlains],
  },

  // ===== LOWLANDS - Tier 2 (NEW) =====
  [EnemyType.SwampToad]: {
    type: EnemyType.SwampToad,
    biome: 0,
    name: "Swamp Toad",
    hp: 190,
    speed: 50,
    radius: 13,
    aggroRange: 240,
    leashRange: 420,
    shootCooldown: 1400,
    projectileDamage: 12,
    projectileSpeed: 120,
    projectileRange: 340,
    shootingPattern: ShootingPatternType.SingleAimed,
    movementPattern: MovementPatternType.Orbiter,
    xpValue: 35,
    shape: "circle",
    color: 0x558833,
    difficultyZone: DifficultyZone.Lowlands,
    biomeAffinity: [RealmBiome.WildMarsh, RealmBiome.WildJungle, RealmBiome.WildMeadow],
  },
  [EnemyType.ThornBush]: {
    type: EnemyType.ThornBush,
    biome: 0,
    name: "Thorn Bush",
    hp: 300,
    speed: 20,
    radius: 16,
    aggroRange: 220,
    leashRange: 380,
    shootCooldown: 800,
    projectileDamage: 10,
    projectileSpeed: 120,
    projectileRange: 320,
    shootingPattern: ShootingPatternType.Spiral3,
    movementPattern: MovementPatternType.SpiralSpinner,
    xpValue: 45,
    shape: "hexagon",
    color: 0x336622,
    difficultyZone: DifficultyZone.Lowlands,
    biomeAffinity: [RealmBiome.WildForest, RealmBiome.WildMeadow, RealmBiome.WildShrubland],
  },
  [EnemyType.DesertScorpion]: {
    type: EnemyType.DesertScorpion,
    biome: 0,
    name: "Desert Scorpion",
    hp: 200,
    speed: 75,
    radius: 13,
    aggroRange: 260,
    leashRange: 440,
    shootCooldown: 1300,
    projectileDamage: 14,
    projectileSpeed: 120,
    projectileRange: 350,
    shootingPattern: ShootingPatternType.Spread3,
    movementPattern: MovementPatternType.ChargerRetreater,
    idleIntensity: IdleIntensity.Medium,
    xpValue: 35,
    shape: "triangle",
    color: 0xcc9944,
    difficultyZone: DifficultyZone.Lowlands,
    biomeAffinity: [RealmBiome.WildDesert, RealmBiome.WildPlains, RealmBiome.WildCliffs],
  },

  // ===== MIDLANDS - Tier 3 (NEW) =====
  [EnemyType.StoneGolem]: {
    type: EnemyType.StoneGolem,
    biome: 0,
    name: "Stone Golem",
    hp: 1200,
    speed: 20,
    radius: 22,
    aggroRange: 240,
    leashRange: 400,
    shootCooldown: 1600,
    projectileDamage: 20,
    projectileSpeed: 120,
    projectileRange: 400,
    shootingPattern: ShootingPatternType.BurstRing8,
    movementPattern: MovementPatternType.SpiralSpinner,
    xpValue: 120,
    shape: "square",
    color: 0x888877,
    difficultyZone: DifficultyZone.Midlands,
    biomeAffinity: [RealmBiome.WildCliffs, RealmBiome.WildShrubland, RealmBiome.WildTundra],
  },
  [EnemyType.VenomSpitter]: {
    type: EnemyType.VenomSpitter,
    biome: 0,
    name: "Venom Spitter",
    hp: 550,
    speed: 65,
    radius: 13,
    aggroRange: 300,
    leashRange: 500,
    shootCooldown: 1100,
    projectileDamage: 18,
    projectileSpeed: 120,
    projectileRange: 420,
    shootingPattern: ShootingPatternType.Spread5,
    movementPattern: MovementPatternType.Shotgunner,
    xpValue: 80,
    shape: "diamond",
    color: 0x66cc22,
    difficultyZone: DifficultyZone.Midlands,
    biomeAffinity: [RealmBiome.WildJungle, RealmBiome.WildMarsh, RealmBiome.WildForest],
  },
  [EnemyType.SandWraith]: {
    type: EnemyType.SandWraith,
    biome: 0,
    name: "Sand Wraith",
    hp: 650,
    speed: 50,
    radius: 14,
    aggroRange: 320,
    leashRange: 520,
    shootCooldown: 1200,
    projectileDamage: 20,
    projectileSpeed: 120,
    projectileRange: 380,
    shootingPattern: ShootingPatternType.BurstRing4,
    movementPattern: MovementPatternType.BurstMage,
    xpValue: 90,
    shape: "star",
    color: 0xddcc88,
    difficultyZone: DifficultyZone.Midlands,
    biomeAffinity: [RealmBiome.WildDesert, RealmBiome.WildPlains, RealmBiome.WildCliffs],
    defaultDamageType: DamageType.Magic,
  },

  // ===== HIGHLANDS - Tier 4 (NEW) =====
  [EnemyType.IceWraith]: {
    type: EnemyType.IceWraith,
    biome: 0,
    name: "Ice Wraith",
    hp: 1400,
    speed: 70,
    radius: 14,
    aggroRange: 310,
    leashRange: 520,
    shootCooldown: 1000,
    projectileDamage: 24,
    projectileSpeed: 120,
    projectileRange: 420,
    shootingPattern: ShootingPatternType.Spread3,
    movementPattern: MovementPatternType.Orbiter,
    idleIntensity: IdleIntensity.Medium,
    xpValue: 200,
    shape: "diamond",
    color: 0xaaddff,
    difficultyZone: DifficultyZone.Highlands,
    biomeAffinity: [RealmBiome.WildPeaks, RealmBiome.WildTundra, RealmBiome.WildTaiga],
    defaultDamageType: DamageType.Magic,
  },
  [EnemyType.ThunderHawk]: {
    type: EnemyType.ThunderHawk,
    biome: 0,
    name: "Thunder Hawk",
    hp: 1200,
    speed: 110,
    radius: 13,
    aggroRange: 350,
    leashRange: 600,
    shootCooldown: 1200,
    projectileDamage: 28,
    projectileSpeed: 120,
    projectileRange: 440,
    shootingPattern: ShootingPatternType.Spread5,
    movementPattern: MovementPatternType.ChargerRetreater,
    idleIntensity: IdleIntensity.High,
    xpValue: 200,
    shape: "triangle",
    color: 0xffdd44,
    difficultyZone: DifficultyZone.Highlands,
    biomeAffinity: [RealmBiome.WildCliffs, RealmBiome.WildShrubland, RealmBiome.WildVolcanic],
    defaultDamageType: DamageType.Magic,
  },
  [EnemyType.MountainTroll]: {
    type: EnemyType.MountainTroll,
    biome: 0,
    name: "Mountain Troll",
    hp: 3500,
    speed: 40,
    radius: 22,
    aggroRange: 260,
    leashRange: 440,
    shootCooldown: 1400,
    projectileDamage: 30,
    projectileSpeed: 120,
    projectileRange: 400,
    shootingPattern: ShootingPatternType.BurstRing8,
    movementPattern: MovementPatternType.Shotgunner,
    xpValue: 380,
    shape: "square",
    color: 0x665544,
    difficultyZone: DifficultyZone.Highlands,
    biomeAffinity: [RealmBiome.WildTundra, RealmBiome.WildTaiga, RealmBiome.WildCliffs],
  },

  // ===== GODLANDS - Tier 5 (NEW) =====
  [EnemyType.AbyssalEye]: {
    type: EnemyType.AbyssalEye,
    biome: 0,
    name: "Abyssal Eye",
    hp: 5500,
    speed: 60,
    radius: 18,
    aggroRange: 380,
    leashRange: 620,
    shootCooldown: 700,
    projectileDamage: 45,
    projectileSpeed: 120,
    projectileRange: 480,
    shootingPattern: ShootingPatternType.BurstRing12,
    movementPattern: MovementPatternType.Orbiter,
    xpValue: 600,
    shape: "circle",
    color: 0xcc22aa,
    difficultyZone: DifficultyZone.Godlands,
    biomeAffinity: [RealmBiome.WildVolcanic, RealmBiome.WildTundra, RealmBiome.WildCliffs],
    defaultDamageType: DamageType.Magic,
  },
  [EnemyType.ChaosSpawn]: {
    type: EnemyType.ChaosSpawn,
    biome: 0,
    name: "Chaos Spawn",
    hp: 3500,
    speed: 100,
    radius: 16,
    aggroRange: 360,
    leashRange: 600,
    shootCooldown: 600,
    projectileDamage: 40,
    projectileSpeed: 120,
    projectileRange: 460,
    shootingPattern: ShootingPatternType.Spread5,
    movementPattern: MovementPatternType.ChargerRetreater,
    idleIntensity: IdleIntensity.Medium,
    xpValue: 500,
    shape: "triangle",
    color: 0xff2244,
    difficultyZone: DifficultyZone.Godlands,
    biomeAffinity: [RealmBiome.WildVolcanic, RealmBiome.WildPeaks, RealmBiome.WildTundra],
    defaultDamageType: DamageType.Magic,
  },
  [EnemyType.DoomPriest]: {
    type: EnemyType.DoomPriest,
    biome: 0,
    name: "Doom Priest",
    hp: 6500,
    speed: 25,
    radius: 18,
    aggroRange: 340,
    leashRange: 540,
    shootCooldown: 800,
    projectileDamage: 50,
    projectileSpeed: 120,
    projectileRange: 500,
    shootingPattern: ShootingPatternType.Spiral8,
    movementPattern: MovementPatternType.SpiralSpinner,
    xpValue: 700,
    shape: "hexagon",
    color: 0x440066,
    difficultyZone: DifficultyZone.Godlands,
    biomeAffinity: [RealmBiome.WildPeaks, RealmBiome.WildVolcanic, RealmBiome.WildTundra],
    dungeonDrop: DungeonType.VoidSanctum,
    dungeonDropChance: 0.3,
    defaultDamageType: DamageType.Magic,
  },

  // ===== PACK ENEMIES =====

  // --- Lowlands Pack (Tier 2): BriarBeast (leader) + BriarImp (minion) ---
  [EnemyType.BriarBeast]: {
    type: EnemyType.BriarBeast,
    biome: 0,
    name: "Briar Beast",
    hp: 500,
    speed: 25,
    radius: 20,
    aggroRange: 260,
    leashRange: 440,
    shootCooldown: 1600,
    projectileDamage: 14,
    projectileSpeed: 120,
    projectileRange: 380,
    shootingPattern: ShootingPatternType.BurstRing8,
    movementPattern: MovementPatternType.RingPulser,
    xpValue: 65,
    shape: "hexagon",
    color: 0x556b2f,
    difficultyZone: DifficultyZone.Lowlands,
    biomeAffinity: [RealmBiome.WildForest, RealmBiome.WildMeadow, RealmBiome.WildShrubland],
  },
  [EnemyType.BriarImp]: {
    type: EnemyType.BriarImp,
    biome: 0,
    name: "Briar Imp",
    hp: 60,
    speed: 100,
    radius: 9,
    aggroRange: 240,
    leashRange: 420,
    shootCooldown: 1400,
    projectileDamage: 10,
    projectileSpeed: 120,
    projectileRange: 300,
    shootingPattern: ShootingPatternType.SingleAimed,
    movementPattern: MovementPatternType.ChargerRetreater,
    idleIntensity: IdleIntensity.High,
    xpValue: 12,
    shape: "triangle",
    color: 0x6b8e23,
    // No difficultyZone/biomeAffinity — never spawns independently
  },

  // --- Midlands Pack (Tier 3): BroodMother (leader) + Broodling (minion) ---
  [EnemyType.BroodMother]: {
    type: EnemyType.BroodMother,
    biome: 0,
    name: "Brood Mother",
    hp: 1500,
    speed: 20,
    radius: 22,
    aggroRange: 300,
    leashRange: 500,
    shootCooldown: 1200,
    projectileDamage: 22,
    projectileSpeed: 120,
    projectileRange: 420,
    shootingPattern: ShootingPatternType.Spiral5,
    movementPattern: MovementPatternType.SpiralSpinner,
    xpValue: 140,
    shape: "star",
    color: 0x4a2040,
    difficultyZone: DifficultyZone.Midlands,
    biomeAffinity: [RealmBiome.WildJungle, RealmBiome.WildForest, RealmBiome.WildMarsh],
    defaultDamageType: DamageType.Magic,
  },
  [EnemyType.Broodling]: {
    type: EnemyType.Broodling,
    biome: 0,
    name: "Broodling",
    hp: 120,
    speed: 110,
    radius: 8,
    aggroRange: 280,
    leashRange: 460,
    shootCooldown: 1400,
    projectileDamage: 14,
    projectileSpeed: 120,
    projectileRange: 340,
    shootingPattern: ShootingPatternType.Spread3,
    movementPattern: MovementPatternType.ChargerRetreater,
    idleIntensity: IdleIntensity.Medium,
    xpValue: 20,
    shape: "diamond",
    color: 0x6a3050,
    // No difficultyZone/biomeAffinity — never spawns independently
  },

  // --- Highlands Pack (Tier 4): FrostMatriarch (leader) + FrostSprite (minion) ---
  [EnemyType.FrostMatriarch]: {
    type: EnemyType.FrostMatriarch,
    biome: 0,
    name: "Frost Matriarch",
    hp: 3800,
    speed: 30,
    radius: 22,
    aggroRange: 320,
    leashRange: 540,
    shootCooldown: 1200,
    projectileDamage: 28,
    projectileSpeed: 120,
    projectileRange: 450,
    shootingPattern: ShootingPatternType.BurstRing12,
    movementPattern: MovementPatternType.Shotgunner,
    xpValue: 400,
    shape: "star",
    color: 0x4488bb,
    difficultyZone: DifficultyZone.Highlands,
    biomeAffinity: [RealmBiome.WildPeaks, RealmBiome.WildTundra, RealmBiome.WildTaiga],
    defaultDamageType: DamageType.Magic,
  },
  [EnemyType.FrostSprite]: {
    type: EnemyType.FrostSprite,
    biome: 0,
    name: "Frost Sprite",
    hp: 250,
    speed: 120,
    radius: 9,
    aggroRange: 300,
    leashRange: 500,
    shootCooldown: 1200,
    projectileDamage: 18,
    projectileSpeed: 120,
    projectileRange: 360,
    shootingPattern: ShootingPatternType.SingleAimed,
    movementPattern: MovementPatternType.Orbiter,
    idleIntensity: IdleIntensity.High,
    xpValue: 30,
    shape: "diamond",
    color: 0x66aadd,
    defaultDamageType: DamageType.Magic,
    // No difficultyZone/biomeAffinity — never spawns independently
  },

  // ========================================================================
  // ===== REALM TIER 2: THE RUINS ==========================================
  // ========================================================================

  // ===== SHORE - T2 =====
  [EnemyType.RuinCrawler]: {
    type: EnemyType.RuinCrawler,
    biome: 0,
    name: "Ruin Crawler",
    hp: 180,
    speed: 45,
    radius: 14,
    aggroRange: 200,
    leashRange: 380,
    shootCooldown: 1800,
    projectileDamage: 22,
    projectileSpeed: 120,
    projectileRange: 320,
    shootingPattern: ShootingPatternType.SingleAimed,
    movementPattern: MovementPatternType.WanderingSprayer,
    xpValue: 25,
    shape: "circle",
    color: 0x8a6a4a,
    difficultyZone: DifficultyZone.Shore,
    biomeAffinity: [RealmBiome.RuinsDustlands, RealmBiome.RuinsBarrens],
    realmTier: RealmTier.Ruins,
  },
  [EnemyType.AshScarab]: {
    type: EnemyType.AshScarab,
    biome: 0,
    name: "Ash Scarab",
    hp: 130,
    speed: 65,
    radius: 11,
    aggroRange: 220,
    leashRange: 360,
    shootCooldown: 2000,
    projectileDamage: 18,
    projectileSpeed: 120,
    projectileRange: 300,
    shootingPattern: ShootingPatternType.Spread3,
    movementPattern: MovementPatternType.Shotgunner,
    xpValue: 22,
    shape: "diamond",
    color: 0x665544,
    difficultyZone: DifficultyZone.Shore,
    biomeAffinity: [RealmBiome.RuinsDustlands, RealmBiome.RuinsBarrens],
    realmTier: RealmTier.Ruins,
  },
  [EnemyType.DustWraith]: {
    type: EnemyType.DustWraith,
    biome: 0,
    name: "Dust Wraith",
    hp: 150,
    speed: 50,
    radius: 12,
    aggroRange: 210,
    leashRange: 370,
    shootCooldown: 1900,
    projectileDamage: 20,
    projectileSpeed: 120,
    projectileRange: 310,
    shootingPattern: ShootingPatternType.BurstRing4,
    movementPattern: MovementPatternType.RingPulser,
    xpValue: 24,
    shape: "triangle",
    color: 0x998877,
    difficultyZone: DifficultyZone.Shore,
    biomeAffinity: [RealmBiome.RuinsDustlands, RealmBiome.RuinsBarrens],
    defaultDamageType: DamageType.Magic,
    realmTier: RealmTier.Ruins,
  },

  // ===== LOWLANDS - T2 =====
  [EnemyType.CursedArcher]: {
    type: EnemyType.CursedArcher,
    biome: 0,
    name: "Cursed Archer",
    hp: 800,
    speed: 80,
    radius: 14,
    aggroRange: 300,
    leashRange: 500,
    shootCooldown: 1100,
    projectileDamage: 28,
    projectileSpeed: 120,
    projectileRange: 400,
    shootingPattern: ShootingPatternType.SingleAimed,
    movementPattern: MovementPatternType.WanderingSprayer,
    idleIntensity: IdleIntensity.Medium,
    xpValue: 100,
    shape: "triangle",
    color: 0x6a5a4a,
    difficultyZone: DifficultyZone.Lowlands,
    biomeAffinity: [RealmBiome.RuinsDustlands, RealmBiome.RuinsBog, RealmBiome.RuinsBarrens],
    realmTier: RealmTier.Ruins,
  },
  [EnemyType.RuinedGolem]: {
    type: EnemyType.RuinedGolem,
    biome: 0,
    name: "Ruined Golem",
    hp: 1200,
    speed: 25,
    radius: 18,
    aggroRange: 240,
    leashRange: 420,
    shootCooldown: 1600,
    projectileDamage: 24,
    projectileSpeed: 120,
    projectileRange: 380,
    shootingPattern: ShootingPatternType.BurstRing4,
    movementPattern: MovementPatternType.RingPulser,
    xpValue: 120,
    shape: "square",
    color: 0x776655,
    difficultyZone: DifficultyZone.Lowlands,
    biomeAffinity: [RealmBiome.RuinsDustlands, RealmBiome.RuinsBog, RealmBiome.RuinsBarrens],
    realmTier: RealmTier.Ruins,
  },
  [EnemyType.BlightedVine]: {
    type: EnemyType.BlightedVine,
    biome: 0,
    name: "Blighted Vine",
    hp: 900,
    speed: 20,
    radius: 16,
    aggroRange: 230,
    leashRange: 400,
    shootCooldown: 900,
    projectileDamage: 22,
    projectileSpeed: 120,
    projectileRange: 350,
    shootingPattern: ShootingPatternType.Spiral3,
    movementPattern: MovementPatternType.SpiralSpinner,
    xpValue: 110,
    shape: "hexagon",
    color: 0x4a5a2a,
    difficultyZone: DifficultyZone.Lowlands,
    biomeAffinity: [RealmBiome.RuinsDustlands, RealmBiome.RuinsBog, RealmBiome.RuinsBarrens],
    realmTier: RealmTier.Ruins,
  },

  // ===== MIDLANDS - T2 =====
  [EnemyType.TombGuard]: {
    type: EnemyType.TombGuard,
    biome: 0,
    name: "Tomb Guard",
    hp: 3500,
    speed: 35,
    radius: 20,
    aggroRange: 270,
    leashRange: 450,
    shootCooldown: 1300,
    projectileDamage: 32,
    projectileSpeed: 120,
    projectileRange: 420,
    shootingPattern: ShootingPatternType.Spread5,
    movementPattern: MovementPatternType.SpiralSpinner,
    xpValue: 280,
    shape: "square",
    color: 0x5a4a3a,
    difficultyZone: DifficultyZone.Midlands,
    biomeAffinity: [RealmBiome.RuinsCatacombs, RealmBiome.RuinsWasteland, RealmBiome.RuinsDesolation],
    realmTier: RealmTier.Ruins,
  },
  [EnemyType.SandPhantom]: {
    type: EnemyType.SandPhantom,
    biome: 0,
    name: "Sand Phantom",
    hp: 2000,
    speed: 85,
    radius: 14,
    aggroRange: 320,
    leashRange: 520,
    shootCooldown: 800,
    projectileDamage: 30,
    projectileSpeed: 120,
    projectileRange: 420,
    shootingPattern: ShootingPatternType.DoubleSingle,
    movementPattern: MovementPatternType.BurstMage,
    idleIntensity: IdleIntensity.Medium,
    xpValue: 250,
    shape: "diamond",
    color: 0xbbaa77,
    difficultyZone: DifficultyZone.Midlands,
    biomeAffinity: [RealmBiome.RuinsCatacombs, RealmBiome.RuinsWasteland, RealmBiome.RuinsDesolation],
    defaultDamageType: DamageType.Magic,
    realmTier: RealmTier.Ruins,
  },
  [EnemyType.CursedObelisk]: {
    type: EnemyType.CursedObelisk,
    biome: 0,
    name: "Cursed Obelisk",
    hp: 2800,
    speed: 15,
    radius: 18,
    aggroRange: 280,
    leashRange: 460,
    shootCooldown: 1200,
    projectileDamage: 28,
    projectileSpeed: 120,
    projectileRange: 400,
    shootingPattern: ShootingPatternType.BurstRing8,
    movementPattern: MovementPatternType.RingPulser,
    xpValue: 270,
    shape: "hexagon",
    color: 0x443322,
    difficultyZone: DifficultyZone.Midlands,
    biomeAffinity: [RealmBiome.RuinsCatacombs, RealmBiome.RuinsWasteland, RealmBiome.RuinsDesolation],
    defaultDamageType: DamageType.Magic,
    realmTier: RealmTier.Ruins,
  },

  // ===== HIGHLANDS - T2 =====
  [EnemyType.ObsidianSentinel]: {
    type: EnemyType.ObsidianSentinel,
    biome: 0,
    name: "Obsidian Sentinel",
    hp: 6500,
    speed: 40,
    radius: 22,
    aggroRange: 300,
    leashRange: 500,
    shootCooldown: 1100,
    projectileDamage: 38,
    projectileSpeed: 120,
    projectileRange: 450,
    shootingPattern: ShootingPatternType.BurstRing8,
    movementPattern: MovementPatternType.Shotgunner,
    xpValue: 600,
    shape: "square",
    color: 0x2a2a3a,
    difficultyZone: DifficultyZone.Highlands,
    biomeAffinity: [RealmBiome.RuinsObsidian, RealmBiome.RuinsFrostfall, RealmBiome.RuinsAshlands],
    realmTier: RealmTier.Ruins,
  },
  [EnemyType.StormCaller]: {
    type: EnemyType.StormCaller,
    biome: 0,
    name: "Storm Caller",
    hp: 4500,
    speed: 55,
    radius: 16,
    aggroRange: 340,
    leashRange: 560,
    shootCooldown: 900,
    projectileDamage: 36,
    projectileSpeed: 120,
    projectileRange: 440,
    shootingPattern: ShootingPatternType.BurstRing12,
    movementPattern: MovementPatternType.BurstMage,
    xpValue: 550,
    shape: "star",
    color: 0x6677aa,
    difficultyZone: DifficultyZone.Highlands,
    biomeAffinity: [RealmBiome.RuinsObsidian, RealmBiome.RuinsFrostfall, RealmBiome.RuinsAshlands],
    defaultDamageType: DamageType.Magic,
    realmTier: RealmTier.Ruins,
  },
  [EnemyType.AshDrake]: {
    type: EnemyType.AshDrake,
    biome: 0,
    name: "Ash Drake",
    hp: 3800,
    speed: 95,
    radius: 14,
    aggroRange: 350,
    leashRange: 580,
    shootCooldown: 800,
    projectileDamage: 34,
    projectileSpeed: 120,
    projectileRange: 430,
    shootingPattern: ShootingPatternType.Spread5,
    movementPattern: MovementPatternType.Orbiter,
    idleIntensity: IdleIntensity.Medium,
    xpValue: 500,
    shape: "triangle",
    color: 0x885533,
    difficultyZone: DifficultyZone.Highlands,
    biomeAffinity: [RealmBiome.RuinsObsidian, RealmBiome.RuinsFrostfall, RealmBiome.RuinsAshlands],
    realmTier: RealmTier.Ruins,
  },

  // ===== GODLANDS - T2 =====
  [EnemyType.RuinLord]: {
    type: EnemyType.RuinLord,
    biome: 0,
    name: "Ruin Lord",
    hp: 12000,
    speed: 60,
    radius: 20,
    aggroRange: 400,
    leashRange: 640,
    shootCooldown: 800,
    projectileDamage: 55,
    projectileSpeed: 120,
    projectileRange: 500,
    shootingPattern: ShootingPatternType.BurstRing8,
    movementPattern: MovementPatternType.Shotgunner,
    xpValue: 1200,
    shape: "star",
    color: 0xaa7733,
    difficultyZone: DifficultyZone.Godlands,
    biomeAffinity: [RealmBiome.RuinsShadowlands, RealmBiome.RuinsDarkSpire, RealmBiome.RuinsVoidEdge],
    defaultDamageType: DamageType.Magic,
    realmTier: RealmTier.Ruins,
  },
  [EnemyType.VoidHerald]: {
    type: EnemyType.VoidHerald,
    biome: 0,
    name: "Void Herald",
    hp: 8000,
    speed: 90,
    radius: 14,
    aggroRange: 380,
    leashRange: 600,
    shootCooldown: 500,
    projectileDamage: 48,
    projectileSpeed: 120,
    projectileRange: 480,
    shootingPattern: ShootingPatternType.Spread5,
    movementPattern: MovementPatternType.BurstMage,
    idleIntensity: IdleIntensity.Medium,
    xpValue: 1000,
    shape: "diamond",
    color: 0x7722aa,
    difficultyZone: DifficultyZone.Godlands,
    biomeAffinity: [RealmBiome.RuinsShadowlands, RealmBiome.RuinsDarkSpire, RealmBiome.RuinsVoidEdge],
    defaultDamageType: DamageType.Magic,
    realmTier: RealmTier.Ruins,
    dungeonDrop: DungeonType.VoidSanctum,
    dungeonDropChance: 0.3,
  },
  [EnemyType.ForgottenTitan]: {
    type: EnemyType.ForgottenTitan,
    biome: 0,
    name: "Forgotten Titan",
    hp: 15000,
    speed: 25,
    radius: 24,
    aggroRange: 340,
    leashRange: 540,
    shootCooldown: 1000,
    projectileDamage: 60,
    projectileSpeed: 120,
    projectileRange: 520,
    shootingPattern: ShootingPatternType.Spiral8,
    movementPattern: MovementPatternType.RingPulser,
    xpValue: 1500,
    shape: "square",
    color: 0x554422,
    difficultyZone: DifficultyZone.Godlands,
    biomeAffinity: [RealmBiome.RuinsShadowlands, RealmBiome.RuinsDarkSpire, RealmBiome.RuinsVoidEdge],
    realmTier: RealmTier.Ruins,
    dungeonDrop: DungeonType.InfernalPit,
    dungeonDropChance: 0.3,
  },

  // ===== T2 PACK: Lowlands =====
  [EnemyType.PlagueBrood]: {
    type: EnemyType.PlagueBrood,
    biome: 0,
    name: "Plague Brood",
    hp: 1400,
    speed: 25,
    radius: 20,
    aggroRange: 270,
    leashRange: 460,
    shootCooldown: 1500,
    projectileDamage: 26,
    projectileSpeed: 120,
    projectileRange: 380,
    shootingPattern: ShootingPatternType.BurstRing8,
    movementPattern: MovementPatternType.RingPulser,
    xpValue: 140,
    shape: "hexagon",
    color: 0x4a6a2a,
    difficultyZone: DifficultyZone.Lowlands,
    biomeAffinity: [RealmBiome.RuinsDustlands, RealmBiome.RuinsBog, RealmBiome.RuinsBarrens],
    realmTier: RealmTier.Ruins,
  },
  [EnemyType.PlagueRat]: {
    type: EnemyType.PlagueRat,
    biome: 0,
    name: "Plague Rat",
    hp: 200,
    speed: 110,
    radius: 9,
    aggroRange: 250,
    leashRange: 430,
    shootCooldown: 1300,
    projectileDamage: 20,
    projectileSpeed: 120,
    projectileRange: 300,
    shootingPattern: ShootingPatternType.SingleAimed,
    movementPattern: MovementPatternType.ChargerRetreater,
    idleIntensity: IdleIntensity.High,
    xpValue: 30,
    shape: "triangle",
    color: 0x5a7a3a,
    realmTier: RealmTier.Ruins,
  },

  // ===== T2 PACK: Midlands =====
  [EnemyType.CursedMatron]: {
    type: EnemyType.CursedMatron,
    biome: 0,
    name: "Cursed Matron",
    hp: 3800,
    speed: 20,
    radius: 22,
    aggroRange: 310,
    leashRange: 510,
    shootCooldown: 1100,
    projectileDamage: 30,
    projectileSpeed: 120,
    projectileRange: 420,
    shootingPattern: ShootingPatternType.Spiral5,
    movementPattern: MovementPatternType.SpiralSpinner,
    xpValue: 300,
    shape: "star",
    color: 0x553344,
    difficultyZone: DifficultyZone.Midlands,
    biomeAffinity: [RealmBiome.RuinsCatacombs, RealmBiome.RuinsWasteland, RealmBiome.RuinsDesolation],
    defaultDamageType: DamageType.Magic,
    realmTier: RealmTier.Ruins,
  },
  [EnemyType.CursedSpawn]: {
    type: EnemyType.CursedSpawn,
    biome: 0,
    name: "Cursed Spawn",
    hp: 400,
    speed: 115,
    radius: 8,
    aggroRange: 290,
    leashRange: 470,
    shootCooldown: 1300,
    projectileDamage: 24,
    projectileSpeed: 120,
    projectileRange: 340,
    shootingPattern: ShootingPatternType.Spread3,
    movementPattern: MovementPatternType.ChargerRetreater,
    idleIntensity: IdleIntensity.Medium,
    xpValue: 50,
    shape: "diamond",
    color: 0x664455,
    realmTier: RealmTier.Ruins,
  },

  // ===== T2 PACK: Highlands =====
  [EnemyType.AshMatriarch]: {
    type: EnemyType.AshMatriarch,
    biome: 0,
    name: "Ash Matriarch",
    hp: 7500,
    speed: 30,
    radius: 22,
    aggroRange: 330,
    leashRange: 550,
    shootCooldown: 1100,
    projectileDamage: 36,
    projectileSpeed: 120,
    projectileRange: 460,
    shootingPattern: ShootingPatternType.BurstRing12,
    movementPattern: MovementPatternType.Shotgunner,
    xpValue: 650,
    shape: "star",
    color: 0x884422,
    difficultyZone: DifficultyZone.Highlands,
    biomeAffinity: [RealmBiome.RuinsObsidian, RealmBiome.RuinsFrostfall, RealmBiome.RuinsAshlands],
    defaultDamageType: DamageType.Magic,
    realmTier: RealmTier.Ruins,
  },
  [EnemyType.AshSprite]: {
    type: EnemyType.AshSprite,
    biome: 0,
    name: "Ash Sprite",
    hp: 600,
    speed: 120,
    radius: 9,
    aggroRange: 310,
    leashRange: 510,
    shootCooldown: 1100,
    projectileDamage: 28,
    projectileSpeed: 120,
    projectileRange: 380,
    shootingPattern: ShootingPatternType.SingleAimed,
    movementPattern: MovementPatternType.Orbiter,
    idleIntensity: IdleIntensity.High,
    xpValue: 80,
    shape: "diamond",
    color: 0xaa6633,
    defaultDamageType: DamageType.Magic,
    realmTier: RealmTier.Ruins,
  },

  // ========================================================================
  // ===== REALM TIER 3: DEVINE HELL ========================================
  // ========================================================================

  // ===== SHORE - T3 =====
  [EnemyType.HellCrab]: {
    type: EnemyType.HellCrab,
    biome: 0,
    name: "Hell Crab",
    hp: 500,
    speed: 50,
    radius: 14,
    aggroRange: 220,
    leashRange: 400,
    shootCooldown: 1600,
    projectileDamage: 40,
    projectileSpeed: 120,
    projectileRange: 340,
    shootingPattern: ShootingPatternType.Spread3,
    movementPattern: MovementPatternType.ChargerRetreater,
    xpValue: 60,
    shape: "circle",
    color: 0xaa2211,
    difficultyZone: DifficultyZone.Shore,
    biomeAffinity: [RealmBiome.HellBrimstone, RealmBiome.HellCinder],
    realmTier: RealmTier.DevineHell,
  },
  [EnemyType.MagmaSlug]: {
    type: EnemyType.MagmaSlug,
    biome: 0,
    name: "Magma Slug",
    hp: 400,
    speed: 30,
    radius: 12,
    aggroRange: 200,
    leashRange: 370,
    shootCooldown: 1800,
    projectileDamage: 35,
    projectileSpeed: 120,
    projectileRange: 320,
    shootingPattern: ShootingPatternType.BurstRing4,
    movementPattern: MovementPatternType.RingPulser,
    xpValue: 55,
    shape: "hexagon",
    color: 0xcc4411,
    difficultyZone: DifficultyZone.Shore,
    biomeAffinity: [RealmBiome.HellBrimstone, RealmBiome.HellCinder],
    defaultDamageType: DamageType.Magic,
    realmTier: RealmTier.DevineHell,
  },
  [EnemyType.EmberWisp]: {
    type: EnemyType.EmberWisp,
    biome: 0,
    name: "Ember Wisp",
    hp: 300,
    speed: 75,
    radius: 10,
    aggroRange: 230,
    leashRange: 390,
    shootCooldown: 1700,
    projectileDamage: 32,
    projectileSpeed: 120,
    projectileRange: 330,
    shootingPattern: ShootingPatternType.SingleAimed,
    movementPattern: MovementPatternType.WanderingSprayer,
    idleIntensity: IdleIntensity.High,
    xpValue: 50,
    shape: "diamond",
    color: 0xff6622,
    difficultyZone: DifficultyZone.Shore,
    biomeAffinity: [RealmBiome.HellBrimstone, RealmBiome.HellCinder],
    defaultDamageType: DamageType.Magic,
    realmTier: RealmTier.DevineHell,
  },

  // ===== LOWLANDS - T3 =====
  [EnemyType.DemonHound]: {
    type: EnemyType.DemonHound,
    biome: 0,
    name: "Demon Hound",
    hp: 2500,
    speed: 95,
    radius: 14,
    aggroRange: 320,
    leashRange: 520,
    shootCooldown: 1000,
    projectileDamage: 45,
    projectileSpeed: 120,
    projectileRange: 400,
    shootingPattern: ShootingPatternType.SingleAimed,
    movementPattern: MovementPatternType.ChargerRetreater,
    idleIntensity: IdleIntensity.Medium,
    xpValue: 250,
    shape: "triangle",
    color: 0x881111,
    difficultyZone: DifficultyZone.Lowlands,
    biomeAffinity: [RealmBiome.HellBrimstone, RealmBiome.HellCinder, RealmBiome.HellEmberfield],
    realmTier: RealmTier.DevineHell,
  },
  [EnemyType.HellfireImp]: {
    type: EnemyType.HellfireImp,
    biome: 0,
    name: "Hellfire Imp",
    hp: 1800,
    speed: 70,
    radius: 12,
    aggroRange: 280,
    leashRange: 460,
    shootCooldown: 1200,
    projectileDamage: 42,
    projectileSpeed: 120,
    projectileRange: 380,
    shootingPattern: ShootingPatternType.Spread3,
    movementPattern: MovementPatternType.Orbiter,
    xpValue: 220,
    shape: "diamond",
    color: 0xcc3322,
    difficultyZone: DifficultyZone.Lowlands,
    biomeAffinity: [RealmBiome.HellBrimstone, RealmBiome.HellCinder, RealmBiome.HellEmberfield],
    defaultDamageType: DamageType.Magic,
    realmTier: RealmTier.DevineHell,
  },
  [EnemyType.BrimstoneGolem]: {
    type: EnemyType.BrimstoneGolem,
    biome: 0,
    name: "Brimstone Golem",
    hp: 3500,
    speed: 25,
    radius: 18,
    aggroRange: 260,
    leashRange: 440,
    shootCooldown: 1500,
    projectileDamage: 48,
    projectileSpeed: 120,
    projectileRange: 400,
    shootingPattern: ShootingPatternType.BurstRing8,
    movementPattern: MovementPatternType.SpiralSpinner,
    xpValue: 280,
    shape: "square",
    color: 0x664422,
    difficultyZone: DifficultyZone.Lowlands,
    biomeAffinity: [RealmBiome.HellBrimstone, RealmBiome.HellCinder, RealmBiome.HellEmberfield],
    realmTier: RealmTier.DevineHell,
  },

  // ===== MIDLANDS - T3 =====
  [EnemyType.InfernalKnight]: {
    type: EnemyType.InfernalKnight,
    biome: 0,
    name: "Infernal Knight",
    hp: 8000,
    speed: 40,
    radius: 20,
    aggroRange: 300,
    leashRange: 480,
    shootCooldown: 1200,
    projectileDamage: 55,
    projectileSpeed: 120,
    projectileRange: 440,
    shootingPattern: ShootingPatternType.Spread5,
    movementPattern: MovementPatternType.Shotgunner,
    xpValue: 600,
    shape: "square",
    color: 0x661111,
    difficultyZone: DifficultyZone.Midlands,
    biomeAffinity: [RealmBiome.HellInferno, RealmBiome.HellDemonforge, RealmBiome.HellBloodmire],
    realmTier: RealmTier.DevineHell,
  },
  [EnemyType.LavaWyrm]: {
    type: EnemyType.LavaWyrm,
    biome: 0,
    name: "Lava Wyrm",
    hp: 5500,
    speed: 80,
    radius: 16,
    aggroRange: 340,
    leashRange: 540,
    shootCooldown: 700,
    projectileDamage: 50,
    projectileSpeed: 120,
    projectileRange: 440,
    shootingPattern: ShootingPatternType.DoubleSingle,
    movementPattern: MovementPatternType.BurstMage,
    idleIntensity: IdleIntensity.Medium,
    xpValue: 520,
    shape: "diamond",
    color: 0xff4400,
    difficultyZone: DifficultyZone.Midlands,
    biomeAffinity: [RealmBiome.HellInferno, RealmBiome.HellDemonforge, RealmBiome.HellBloodmire],
    defaultDamageType: DamageType.Magic,
    realmTier: RealmTier.DevineHell,
  },
  [EnemyType.SoulReaper]: {
    type: EnemyType.SoulReaper,
    biome: 0,
    name: "Soul Reaper",
    hp: 6000,
    speed: 50,
    radius: 18,
    aggroRange: 320,
    leashRange: 520,
    shootCooldown: 1000,
    projectileDamage: 52,
    projectileSpeed: 120,
    projectileRange: 460,
    shootingPattern: ShootingPatternType.BurstRing8,
    movementPattern: MovementPatternType.SpiralSpinner,
    xpValue: 550,
    shape: "hexagon",
    color: 0x440044,
    difficultyZone: DifficultyZone.Midlands,
    biomeAffinity: [RealmBiome.HellInferno, RealmBiome.HellDemonforge, RealmBiome.HellBloodmire],
    defaultDamageType: DamageType.Magic,
    realmTier: RealmTier.DevineHell,
  },

  // ===== HIGHLANDS - T3 =====
  [EnemyType.AbyssalLord]: {
    type: EnemyType.AbyssalLord,
    biome: 0,
    name: "Abyssal Lord",
    hp: 15000,
    speed: 45,
    radius: 22,
    aggroRange: 340,
    leashRange: 560,
    shootCooldown: 900,
    projectileDamage: 65,
    projectileSpeed: 120,
    projectileRange: 480,
    shootingPattern: ShootingPatternType.BurstRing12,
    movementPattern: MovementPatternType.BurstMage,
    xpValue: 1200,
    shape: "star",
    color: 0x330044,
    difficultyZone: DifficultyZone.Highlands,
    biomeAffinity: [RealmBiome.HellAbyssal, RealmBiome.HellDoomspire, RealmBiome.HellSoulfire],
    defaultDamageType: DamageType.Magic,
    realmTier: RealmTier.DevineHell,
  },
  [EnemyType.HellfireDrake]: {
    type: EnemyType.HellfireDrake,
    biome: 0,
    name: "Hellfire Drake",
    hp: 10000,
    speed: 100,
    radius: 16,
    aggroRange: 360,
    leashRange: 600,
    shootCooldown: 600,
    projectileDamage: 60,
    projectileSpeed: 120,
    projectileRange: 460,
    shootingPattern: ShootingPatternType.Spread5,
    movementPattern: MovementPatternType.Orbiter,
    idleIntensity: IdleIntensity.Medium,
    xpValue: 1000,
    shape: "triangle",
    color: 0xdd2200,
    difficultyZone: DifficultyZone.Highlands,
    biomeAffinity: [RealmBiome.HellAbyssal, RealmBiome.HellDoomspire, RealmBiome.HellSoulfire],
    realmTier: RealmTier.DevineHell,
  },
  [EnemyType.DoomSentinel]: {
    type: EnemyType.DoomSentinel,
    biome: 0,
    name: "Doom Sentinel",
    hp: 18000,
    speed: 30,
    radius: 24,
    aggroRange: 300,
    leashRange: 500,
    shootCooldown: 1100,
    projectileDamage: 70,
    projectileSpeed: 120,
    projectileRange: 470,
    shootingPattern: ShootingPatternType.BurstRing8,
    movementPattern: MovementPatternType.Shotgunner,
    xpValue: 1400,
    shape: "square",
    color: 0x441100,
    difficultyZone: DifficultyZone.Highlands,
    biomeAffinity: [RealmBiome.HellAbyssal, RealmBiome.HellDoomspire, RealmBiome.HellSoulfire],
    realmTier: RealmTier.DevineHell,
  },

  // ===== GODLANDS - T3 =====
  [EnemyType.ArchDemon]: {
    type: EnemyType.ArchDemon,
    biome: 0,
    name: "Arch Demon",
    hp: 30000,
    speed: 55,
    radius: 22,
    aggroRange: 420,
    leashRange: 660,
    shootCooldown: 700,
    projectileDamage: 80,
    projectileSpeed: 120,
    projectileRange: 520,
    shootingPattern: ShootingPatternType.BurstRing12,
    movementPattern: MovementPatternType.Shotgunner,
    xpValue: 3000,
    shape: "star",
    color: 0xff0000,
    difficultyZone: DifficultyZone.Godlands,
    biomeAffinity: [RealmBiome.HellVoidmaw, RealmBiome.HellChaosrift, RealmBiome.HellAnnihilation],
    defaultDamageType: DamageType.Magic,
    realmTier: RealmTier.DevineHell,
  },
  [EnemyType.VoidEmperor]: {
    type: EnemyType.VoidEmperor,
    biome: 0,
    name: "Void Emperor",
    hp: 20000,
    speed: 85,
    radius: 18,
    aggroRange: 400,
    leashRange: 640,
    shootCooldown: 400,
    projectileDamage: 70,
    projectileSpeed: 120,
    projectileRange: 500,
    shootingPattern: ShootingPatternType.Spiral8,
    movementPattern: MovementPatternType.BurstMage,
    idleIntensity: IdleIntensity.Medium,
    xpValue: 2500,
    shape: "diamond",
    color: 0x6600aa,
    difficultyZone: DifficultyZone.Godlands,
    biomeAffinity: [RealmBiome.HellVoidmaw, RealmBiome.HellChaosrift, RealmBiome.HellAnnihilation],
    defaultDamageType: DamageType.Magic,
    realmTier: RealmTier.DevineHell,
    dungeonDrop: DungeonType.VoidSanctum,
    dungeonDropChance: 0.3,
  },
  [EnemyType.WorldEnder]: {
    type: EnemyType.WorldEnder,
    biome: 0,
    name: "World Ender",
    hp: 35000,
    speed: 25,
    radius: 26,
    aggroRange: 360,
    leashRange: 560,
    shootCooldown: 900,
    projectileDamage: 90,
    projectileSpeed: 120,
    projectileRange: 540,
    shootingPattern: ShootingPatternType.Spiral8,
    movementPattern: MovementPatternType.RingPulser,
    xpValue: 3500,
    shape: "square",
    color: 0x220000,
    difficultyZone: DifficultyZone.Godlands,
    biomeAffinity: [RealmBiome.HellVoidmaw, RealmBiome.HellChaosrift, RealmBiome.HellAnnihilation],
    realmTier: RealmTier.DevineHell,
    dungeonDrop: DungeonType.InfernalPit,
    dungeonDropChance: 0.3,
  },

  // ===== T3 PACK: Lowlands =====
  [EnemyType.DemonBroodmother]: {
    type: EnemyType.DemonBroodmother,
    biome: 0,
    name: "Demon Broodmother",
    hp: 4000,
    speed: 25,
    radius: 22,
    aggroRange: 300,
    leashRange: 480,
    shootCooldown: 1300,
    projectileDamage: 48,
    projectileSpeed: 120,
    projectileRange: 400,
    shootingPattern: ShootingPatternType.BurstRing8,
    movementPattern: MovementPatternType.RingPulser,
    xpValue: 320,
    shape: "hexagon",
    color: 0x771100,
    difficultyZone: DifficultyZone.Lowlands,
    biomeAffinity: [RealmBiome.HellBrimstone, RealmBiome.HellCinder, RealmBiome.HellEmberfield],
    realmTier: RealmTier.DevineHell,
  },
  [EnemyType.DemonWhelp]: {
    type: EnemyType.DemonWhelp,
    biome: 0,
    name: "Demon Whelp",
    hp: 500,
    speed: 115,
    radius: 9,
    aggroRange: 280,
    leashRange: 460,
    shootCooldown: 1200,
    projectileDamage: 38,
    projectileSpeed: 120,
    projectileRange: 320,
    shootingPattern: ShootingPatternType.SingleAimed,
    movementPattern: MovementPatternType.ChargerRetreater,
    idleIntensity: IdleIntensity.High,
    xpValue: 60,
    shape: "triangle",
    color: 0x992211,
    realmTier: RealmTier.DevineHell,
  },

  // ===== T3 PACK: Midlands =====
  [EnemyType.SoulHarvester]: {
    type: EnemyType.SoulHarvester,
    biome: 0,
    name: "Soul Harvester",
    hp: 8000,
    speed: 20,
    radius: 22,
    aggroRange: 330,
    leashRange: 530,
    shootCooldown: 1000,
    projectileDamage: 55,
    projectileSpeed: 120,
    projectileRange: 440,
    shootingPattern: ShootingPatternType.Spiral5,
    movementPattern: MovementPatternType.SpiralSpinner,
    xpValue: 620,
    shape: "star",
    color: 0x330033,
    difficultyZone: DifficultyZone.Midlands,
    biomeAffinity: [RealmBiome.HellInferno, RealmBiome.HellDemonforge, RealmBiome.HellBloodmire],
    defaultDamageType: DamageType.Magic,
    realmTier: RealmTier.DevineHell,
  },
  [EnemyType.LostSoul]: {
    type: EnemyType.LostSoul,
    biome: 0,
    name: "Lost Soul",
    hp: 800,
    speed: 120,
    radius: 8,
    aggroRange: 310,
    leashRange: 500,
    shootCooldown: 1100,
    projectileDamage: 42,
    projectileSpeed: 120,
    projectileRange: 360,
    shootingPattern: ShootingPatternType.Spread3,
    movementPattern: MovementPatternType.ChargerRetreater,
    idleIntensity: IdleIntensity.Medium,
    xpValue: 100,
    shape: "diamond",
    color: 0x550055,
    defaultDamageType: DamageType.Magic,
    realmTier: RealmTier.DevineHell,
  },

  // ===== T3 PACK: Highlands =====
  [EnemyType.DoomMatriarch]: {
    type: EnemyType.DoomMatriarch,
    biome: 0,
    name: "Doom Matriarch",
    hp: 20000,
    speed: 30,
    radius: 24,
    aggroRange: 350,
    leashRange: 570,
    shootCooldown: 1000,
    projectileDamage: 65,
    projectileSpeed: 120,
    projectileRange: 480,
    shootingPattern: ShootingPatternType.BurstRing12,
    movementPattern: MovementPatternType.Shotgunner,
    xpValue: 1500,
    shape: "star",
    color: 0x440000,
    difficultyZone: DifficultyZone.Highlands,
    biomeAffinity: [RealmBiome.HellAbyssal, RealmBiome.HellDoomspire, RealmBiome.HellSoulfire],
    defaultDamageType: DamageType.Magic,
    realmTier: RealmTier.DevineHell,
  },
  [EnemyType.DoomSprite]: {
    type: EnemyType.DoomSprite,
    biome: 0,
    name: "Doom Sprite",
    hp: 1500,
    speed: 125,
    radius: 9,
    aggroRange: 330,
    leashRange: 530,
    shootCooldown: 1000,
    projectileDamage: 50,
    projectileSpeed: 120,
    projectileRange: 400,
    shootingPattern: ShootingPatternType.SingleAimed,
    movementPattern: MovementPatternType.Orbiter,
    idleIntensity: IdleIntensity.High,
    xpValue: 180,
    shape: "diamond",
    color: 0x660000,
    defaultDamageType: DamageType.Magic,
    realmTier: RealmTier.DevineHell,
  },
};

// Merge realm enemy defs into main ENEMY_DEFS
Object.assign(ENEMY_DEFS, REALM_ENEMY_DEFS);

// --- Realm Spawn Config (keyed by DifficultyZone) ---

export interface RealmSpawnConfig {
  maxEnemies: number;
  respawnDelay: number; // ms
}

export const REALM_SPAWN_CONFIG: Record<number, RealmSpawnConfig> = {
  [DifficultyZone.Shore]: { maxEnemies: 160, respawnDelay: 8000 },
  [DifficultyZone.Lowlands]: { maxEnemies: 200, respawnDelay: 7000 },
  [DifficultyZone.Midlands]: { maxEnemies: 180, respawnDelay: 6000 },
  [DifficultyZone.Highlands]: { maxEnemies: 140, respawnDelay: 5000 },
  [DifficultyZone.Godlands]: { maxEnemies: 100, respawnDelay: 5000 },
};

// Helper: get all realm enemy types for a difficulty zone and realm tier
export function getEnemyTypesForDifficultyZone(zone: number, realmTier: number = RealmTier.Wild): number[] {
  const tier = realmTier || RealmTier.Wild;
  return Object.values(REALM_ENEMY_DEFS)
    .filter((def) => def.difficultyZone === zone && (def.realmTier ?? RealmTier.Wild) === tier)
    .map((def) => def.type);
}

// Helper: get realm enemy types matching zone, biome affinity, and realm tier
export function getEnemyTypesForBiomeAndZone(
  biome: number,
  zone: number,
  realmTier: number = RealmTier.Wild
): number[] {
  const tier = realmTier || RealmTier.Wild;
  const matches = Object.values(REALM_ENEMY_DEFS).filter(
    (def) =>
      def.difficultyZone === zone &&
      (def.realmTier ?? RealmTier.Wild) === tier &&
      def.biomeAffinity &&
      def.biomeAffinity.includes(biome)
  );
  // If no biome-specific match, fall back to all enemies in that zone+tier
  if (matches.length === 0) return getEnemyTypesForDifficultyZone(zone, tier);
  return matches.map((def) => def.type);
}

// --- Dungeon Biome Types (separate ID space from overworld) ---

export const DungeonBiomeType = {
  InfernalPit: 100,
  VoidSanctum: 101,
} as const;

// --- Dungeon Enemy Definitions ---

export const DUNGEON_ENEMY_DEFS: Record<number, EnemyDefinition> = {
  // ===== THE INFERNAL PIT =====
  [EnemyType.InfernalHound]: {
    type: EnemyType.InfernalHound,
    biome: DungeonBiomeType.InfernalPit,
    name: "Infernal Hound",
    hp: 2200,
    speed: 120,
    radius: 14,
    aggroRange: 350,
    leashRange: 800,
    shootCooldown: 2200,
    projectileDamage: 28,
    projectileSpeed: 120,
    projectileRange: 200,
    shootingPattern: ShootingPatternType.SingleAimed,
    xpValue: 300,
    shape: "triangle",
    color: 0xff4400,
  },
  [EnemyType.MagmaSerpent]: {
    type: EnemyType.MagmaSerpent,
    biome: DungeonBiomeType.InfernalPit,
    name: "Magma Serpent",
    hp: 3200,
    speed: 100,
    radius: 16,
    aggroRange: 300,
    leashRange: 800,
    shootCooldown: 2800,
    projectileDamage: 32,
    projectileSpeed: 120,
    projectileRange: 220,
    shootingPattern: ShootingPatternType.Spread3,
    xpValue: 400,
    shape: "hexagon",
    color: 0xff6600,
    defaultDamageType: DamageType.Magic,
  },
  [EnemyType.CinderWraith]: {
    type: EnemyType.CinderWraith,
    biome: DungeonBiomeType.InfernalPit,
    name: "Cinder Wraith",
    hp: 1800,
    speed: 140,
    radius: 12,
    aggroRange: 400,
    leashRange: 800,
    shootCooldown: 1800,
    projectileDamage: 24,
    projectileSpeed: 120,
    projectileRange: 200,
    shootingPattern: ShootingPatternType.BurstRing4,
    xpValue: 250,
    shape: "diamond",
    color: 0xffaa22,
    defaultDamageType: DamageType.Magic,
  },
  // BOSS
  [EnemyType.MoltenWyrm]: {
    type: EnemyType.MoltenWyrm,
    biome: DungeonBiomeType.InfernalPit,
    name: "Molten Wyrm",
    hp: 26000,
    speed: 55,
    radius: 30,
    aggroRange: 600,
    leashRange: 1200,
    shootCooldown: 1200,
    projectileDamage: 35,
    projectileSpeed: 120,
    projectileRange: 280,
    shootingPattern: ShootingPatternType.BurstRing8,
    xpValue: 3000,
    shape: "star",
    color: 0xff4400,
    defaultDamageType: DamageType.Magic,
  },

  // ===== THE VOID SANCTUM =====
  [EnemyType.VoidAcolyte]: {
    type: EnemyType.VoidAcolyte,
    biome: DungeonBiomeType.VoidSanctum,
    name: "Void Acolyte",
    hp: 5000,
    speed: 60,
    radius: 14,
    aggroRange: 350,
    leashRange: 800,
    shootCooldown: 800,
    projectileDamage: 40,
    projectileSpeed: 120,
    projectileRange: 420,
    shootingPattern: ShootingPatternType.BurstRing8,
    xpValue: 650,
    shape: "circle",
    color: 0x6622cc,
    defaultDamageType: DamageType.Magic,
  },
  [EnemyType.ShadowWeaver]: {
    type: EnemyType.ShadowWeaver,
    biome: DungeonBiomeType.VoidSanctum,
    name: "Shadow Weaver",
    hp: 3500,
    speed: 90,
    radius: 12,
    aggroRange: 380,
    leashRange: 800,
    shootCooldown: 700,
    projectileDamage: 35,
    projectileSpeed: 120,
    projectileRange: 400,
    shootingPattern: ShootingPatternType.Spread5,
    xpValue: 500,
    shape: "diamond",
    color: 0x8844cc,
    defaultDamageType: DamageType.Magic,
  },
  [EnemyType.AbyssalSentry]: {
    type: EnemyType.AbyssalSentry,
    biome: DungeonBiomeType.VoidSanctum,
    name: "Abyssal Sentry",
    hp: 8000,
    speed: 35,
    radius: 20,
    aggroRange: 300,
    leashRange: 800,
    shootCooldown: 1200,
    projectileDamage: 50,
    projectileSpeed: 120,
    projectileRange: 450,
    shootingPattern: ShootingPatternType.BurstRing12,
    xpValue: 900,
    shape: "square",
    color: 0x4400aa,
    defaultDamageType: DamageType.Magic,
  },
  // BOSS
  [EnemyType.TheArchitect]: {
    type: EnemyType.TheArchitect,
    biome: DungeonBiomeType.VoidSanctum,
    name: "The Architect",
    hp: 55000,
    speed: 30,
    radius: 35,
    aggroRange: 700,
    leashRange: 1200,
    shootCooldown: 1000,
    projectileDamage: 45,
    projectileSpeed: 120,
    projectileRange: 550,
    shootingPattern: ShootingPatternType.Spiral8,
    xpValue: 5000,
    shape: "star",
    color: 0x6600cc,
    defaultDamageType: DamageType.Magic,
  },
  // ADD (spawned by The Architect)
  [EnemyType.VoidMinion]: {
    type: EnemyType.VoidMinion,
    biome: DungeonBiomeType.VoidSanctum,
    name: "Void Minion",
    hp: 400,
    speed: 80,
    radius: 10,
    aggroRange: 400,
    leashRange: 1000,
    shootCooldown: 1200,
    projectileDamage: 25,
    projectileSpeed: 120,
    projectileRange: 350,
    shootingPattern: ShootingPatternType.SingleAimed,
    xpValue: 50,
    shape: "circle",
    color: 0x9944ff,
    defaultDamageType: DamageType.Magic,
  },
  // Destructible switch (stationary, no AI)
  [EnemyType.VoidSwitch]: {
    type: EnemyType.VoidSwitch,
    biome: DungeonBiomeType.VoidSanctum,
    name: "Void Switch",
    hp: 3000,
    speed: 0,
    radius: 18,
    aggroRange: 0,
    leashRange: 0,
    shootCooldown: 999999,
    projectileDamage: 0,
    projectileSpeed: 120,
    projectileRange: 0,
    shootingPattern: ShootingPatternType.SingleAimed,
    xpValue: 100,
    shape: "hexagon",
    color: 0x00ccff,
  },
};

// Merge dungeon defs into main ENEMY_DEFS for lookup
Object.assign(ENEMY_DEFS, DUNGEON_ENEMY_DEFS);

// --- Dungeon Visuals ---

export const DUNGEON_VISUALS: Record<
  number,
  { groundFill: number; tileLineColor: number; tileLineAlpha: number; name: string }
> = {
  [DungeonType.InfernalPit]: {
    groundFill: 0x2e0a0a,
    tileLineColor: 0x4e1a0a,
    tileLineAlpha: 0.4,
    name: "The Infernal Pit",
  },
  [DungeonType.VoidSanctum]: {
    groundFill: 0x0a0a2e,
    tileLineColor: 0x1a0a4e,
    tileLineAlpha: 0.4,
    name: "The Void Sanctum",
  },
};

// --- Dungeon Layouts (pre-placed enemy positions) ---

export interface DungeonEnemyPlacement {
  enemyType: number;
  x: number;
  y: number;
}

export const DUNGEON_LAYOUTS: Record<number, DungeonEnemyPlacement[]> = {
  [DungeonType.InfernalPit]: [
    // Group 1: Near entrance
    { enemyType: EnemyType.InfernalHound, x: 100, y: 1600 },
    { enemyType: EnemyType.CinderWraith, x: 200, y: 1550 },
    { enemyType: EnemyType.InfernalHound, x: 300, y: 1600 },
    // Group 2: Mid-path
    { enemyType: EnemyType.MagmaSerpent, x: 100, y: 1200 },
    { enemyType: EnemyType.InfernalHound, x: 200, y: 1200 },
    { enemyType: EnemyType.CinderWraith, x: 300, y: 1200 },
    // Group 3: Pre-boss
    { enemyType: EnemyType.MagmaSerpent, x: 100, y: 700 },
    { enemyType: EnemyType.MagmaSerpent, x: 300, y: 700 },
    { enemyType: EnemyType.CinderWraith, x: 200, y: 600 },
    { enemyType: EnemyType.InfernalHound, x: 80, y: 600 },
    { enemyType: EnemyType.InfernalHound, x: 320, y: 600 },
  ],
  [DungeonType.VoidSanctum]: [
    // Group 1: Near entrance
    { enemyType: EnemyType.VoidAcolyte, x: 100, y: 1600 },
    { enemyType: EnemyType.VoidAcolyte, x: 300, y: 1600 },
    { enemyType: EnemyType.ShadowWeaver, x: 200, y: 1550 },
    // Group 2: Mid-path
    { enemyType: EnemyType.AbyssalSentry, x: 200, y: 1200 },
    { enemyType: EnemyType.ShadowWeaver, x: 80, y: 1250 },
    { enemyType: EnemyType.ShadowWeaver, x: 320, y: 1250 },
    { enemyType: EnemyType.VoidAcolyte, x: 150, y: 1150 },
    // Group 3: Pre-boss
    { enemyType: EnemyType.AbyssalSentry, x: 80, y: 700 },
    { enemyType: EnemyType.AbyssalSentry, x: 320, y: 700 },
    { enemyType: EnemyType.ShadowWeaver, x: 200, y: 600 },
    { enemyType: EnemyType.VoidAcolyte, x: 120, y: 550 },
    { enemyType: EnemyType.VoidAcolyte, x: 280, y: 550 },
  ],
};

// --- Dungeon Lookup Maps ---

export const DUNGEON_BOSS_TYPE: Record<number, number> = {
  [DungeonType.InfernalPit]: EnemyType.MoltenWyrm,
  [DungeonType.VoidSanctum]: EnemyType.TheArchitect,
};

export const ZONE_TO_DUNGEON: Record<string, number> = {
  [PlayerZone.DungeonInfernal]: DungeonType.InfernalPit,
  [PlayerZone.DungeonVoid]: DungeonType.VoidSanctum,
};

export const DUNGEON_TO_ZONE: Record<number, string> = {
  [DungeonType.InfernalPit]: PlayerZone.DungeonInfernal,
  [DungeonType.VoidSanctum]: PlayerZone.DungeonVoid,
};

// --- Room-Based Dungeon Enemy Config ---
// Each entry corresponds to a room by index:
// InfernalPit: [0] = spawn, [1-7] = normal rooms (3 enemies each), [8] = boss room
// VoidSanctum: [0] = spawn, [1-3] = normal, [4] = switchA, [5] = preBoss, [6] = boss, [7-8] = switches

export interface DungeonRoomEnemyConfig {
  enemies: number[]; // EnemyType values
}

export const DUNGEON_ROOM_ENEMIES: Record<number, DungeonRoomEnemyConfig[]> = {
  [DungeonType.InfernalPit]: [
    // Room 0: spawn room - no enemies
    { enemies: [] },
    // Room 1
    { enemies: [EnemyType.InfernalHound, EnemyType.InfernalHound, EnemyType.InfernalHound] },
    // Room 2
    { enemies: [EnemyType.InfernalHound, EnemyType.CinderWraith, EnemyType.InfernalHound] },
    // Room 3
    { enemies: [EnemyType.MagmaSerpent, EnemyType.InfernalHound, EnemyType.CinderWraith] },
    // Room 4
    { enemies: [EnemyType.CinderWraith, EnemyType.CinderWraith, EnemyType.MagmaSerpent] },
    // Room 5
    { enemies: [EnemyType.MagmaSerpent, EnemyType.MagmaSerpent, EnemyType.CinderWraith] },
    // Room 6
    { enemies: [EnemyType.MagmaSerpent, EnemyType.CinderWraith, EnemyType.InfernalHound] },
    // Room 7
    { enemies: [EnemyType.MagmaSerpent, EnemyType.MagmaSerpent, EnemyType.MagmaSerpent] },
    // Room 8: boss room - boss spawned separately
    { enemies: [] },
  ],
  [DungeonType.VoidSanctum]: [
    // Room 0: spawn room - no enemies
    { enemies: [] },
    // Room 1: first encounter
    { enemies: [EnemyType.VoidAcolyte, EnemyType.VoidAcolyte, EnemyType.ShadowWeaver] },
    // Room 2: mid dungeon
    { enemies: [EnemyType.AbyssalSentry, EnemyType.ShadowWeaver, EnemyType.ShadowWeaver, EnemyType.VoidAcolyte] },
    // Room 3: crossroads (connects to switchA and preBoss)
    { enemies: [EnemyType.AbyssalSentry, EnemyType.AbyssalSentry, EnemyType.ShadowWeaver, EnemyType.VoidAcolyte, EnemyType.VoidAcolyte] },
    // Room 4: switchRoomA (guarded dead-end)
    { enemies: [EnemyType.ShadowWeaver, EnemyType.VoidAcolyte] },
    // Room 5: preBoss room (heavy guard)
    { enemies: [EnemyType.AbyssalSentry, EnemyType.AbyssalSentry, EnemyType.ShadowWeaver, EnemyType.ShadowWeaver] },
    // Room 6: boss room - boss spawned separately after switches
    { enemies: [] },
    // Room 7: switchRoomB (guarded dead-end, left of boss)
    { enemies: [EnemyType.AbyssalSentry, EnemyType.VoidAcolyte] },
    // Room 8: switchRoomC (guarded dead-end, right of boss)
    { enemies: [EnemyType.AbyssalSentry, EnemyType.VoidAcolyte] },
  ],
};

// --- Infernal Pit Normal Room Enemy Variants ---
// Pool of enemy lists for normal rooms (cycled through for variable room counts)
export const INFERNAL_NORMAL_ROOM_VARIANTS: number[][] = [
  [EnemyType.InfernalHound, EnemyType.InfernalHound, EnemyType.InfernalHound],
  [EnemyType.InfernalHound, EnemyType.CinderWraith, EnemyType.InfernalHound],
  [EnemyType.MagmaSerpent, EnemyType.InfernalHound, EnemyType.CinderWraith],
  [EnemyType.CinderWraith, EnemyType.CinderWraith, EnemyType.MagmaSerpent],
  [EnemyType.MagmaSerpent, EnemyType.MagmaSerpent, EnemyType.CinderWraith],
  [EnemyType.MagmaSerpent, EnemyType.CinderWraith, EnemyType.InfernalHound],
  [EnemyType.MagmaSerpent, EnemyType.MagmaSerpent, EnemyType.MagmaSerpent],
];

// --- Dungeon Helpers ---

export function isDungeonZone(zone: string): boolean {
  const base = getZoneBase(zone);
  return base === PlayerZone.DungeonInfernal || base === PlayerZone.DungeonVoid;
}

export function getDungeonTypeFromZone(zone: string): number | undefined {
  return ZONE_TO_DUNGEON[getZoneBase(zone)];
}

export function isBossEnemy(enemyType: number): boolean {
  return enemyType === EnemyType.MoltenWyrm || enemyType === EnemyType.TheArchitect;
}
